name: CD Vercel

env:
  VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

on:
  push:
    branches: ["main", "deploy_cd_test"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run installation
        run: yarn install
      - name: Run deploy
        run: yarn deploy:prod
