name: CI testes implementation 

env:
  VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run installation
        run: yarn install
      - name: Run linter
        run: yarn lint
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run installation
        run: yarn install
      - name: Run Deployment preview
        run: yarn deploy:preview
  teste2e:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with: 
            node-version: 16.13.0
            cache: 'yarn' 
        - name: Run Cypress
          uses: cypress-io/github-action@v4
          with: 
            browser: firefox
