name: Standard formatting check

on: 
  pull_request:
    types: [opened, synchronize]

jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install dependencies 
      - name: Run installation
        run: yarn install

      - name: Run linter
        run: yarn lint
