name: Standard formatting check

on: 
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install dependencies 
      - name: Run Install
        run: yarn install

      - name: Run lint
        run: yarn lint
